### ISSUE TITLE
Frontend functionality

### ISSUE THREAD

**Issue by shadowlion** [DLibatique/CLAS199-old#2]
Skeleton functionality of the file upload

- [x] Create file uploads input for student usage

**Comment by shadowlion** [comment]
@DLibatique Is there anything students need to submit alongside their file? For example, I'm thinking of making a modal window that had a dropdown with a list of student's names they will have to input along with the file upload for submission.

**Comment by DLibatique** [comment]
@shadowlion ~~I originally envisioned taking care of that in the file-naming convention (e.g., explicit guidelines that say you must submit the document with the name:~~

~~[Student Last Name] - Response - [Author Last Name] [Article Year].pdf~~

~~So, for example:~~

~~Libatique - Response - Zuckerberg 2018.pdf~~

~~So essentially just the input for the file upload is necessary, unless you think other elements are advisable?~~

**Comment by DLibatique** [comment]
Scratch what I said above. Yes, it will make sense to allow a text box for a student to input his/her name and attach that name to the file submission.

**Comment by DLibatique** [comment]
@shadowlion not sure exactly it'll look like (is there a way to imbed the name into the metadata of the PDF or doc?)

**Comment by shadowlion** [comment]
@DLibatique how about this - You can have a decided naming convention with your students, but when they upload it, I can programmatically add a timestamp to the name, and that way we have a recorded list of everything that's been uploaded, yeah?

**Comment by DLibatique** [comment]
@shadowlion and in the order it was uploaded -- that sounds great. easier to deal with just the one file-upload input rather than coordinating a file upload and a name textbox, yeah?
